package com.example.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_dark_primary = Color(0xFFFFB4AA)
val md_theme_dark_onPrimary = Color(0xFF690003)
val md_theme_dark_primaryContainer = Color(0xFFE50914)
val md_theme_dark_onPrimaryContainer = Color(0xFFFFF7F6)
val md_theme_dark_secondary = Color(0xFFFFDF9E)
val md_theme_dark_onSecondary = Color(0xFF3F2E00)
val md_theme_dark_secondaryContainer = Color(0xFFFABD00)
val md_theme_dark_onSecondaryContainer = Color(0xFF6A4E00)
val md_theme_dark_tertiary = Color(0xFFA7C8FF)
val md_theme_dark_onTertiary = Color(0xFF003061)
val md_theme_dark_tertiaryContainer = Color(0xFF0072D7)
val md_theme_dark_onTertiaryContainer = Color(0xFFF8F9FF)
val md_theme_dark_error = Color(0xFFFFB4AB)
val md_theme_dark_onError = Color(0xFF690005)
val md_theme_dark_errorContainer = Color(0xFF93000A)
val md_theme_dark_onErrorContainer = Color(0xFFFFDAD6)
val md_theme_dark_background = Color(0xFF200E0C)
val md_theme_dark_onBackground = Color(0xFFFFDAD5)
val md_theme_dark_surface = Color(0xFF200E0C)
val md_theme_dark_onSurface = Color(0xFFFFDAD5)
val md_theme_dark_surfaceVariant = Color(0xFF462F2C)
val md_theme_dark_onSurfaceVariant = Color(0xFFE9BCB6)
val md_theme_dark_outline = Color(0xFFAF8782)
val md_theme_dark_inverseOnSurface = Color(0xFF412B28)
val md_theme_dark_inverseSurface = Color(0xFFFFDAD5)
val md_theme_dark_inversePrimary = Color(0xFFC0000C)
val md_theme_dark_surfaceTint = Color(0xFFFFB4AA)

val md_theme_dark_surfaceDim = Color(0xFF200E0C)
val md_theme_dark_surfaceBright = Color(0xFF4A3330)
val md_theme_dark_surfaceContainerLowest = Color(0xFF1A0908)
val md_theme_dark_surfaceContainerLow = Color(0xFF2A1614)
val md_theme_dark_surfaceContainer = Color(0xFF2E1A18)
val md_theme_dark_surfaceContainerHigh = Color(0xFF3A2522)
val md_theme_dark_surfaceContainerHighest = Color(0xFF462F2C)
